//
//  HJUserLogic.h
//  DxpUserSDK
//
//  Created by 李标 on 2025/11/2.
//  接口调用封装层

#import <Foundation/Foundation.h>
#import "HJUserIdentityInitialModel.h"
#import "HJDeviceReportModel.h"
#import "HJUserIdentityLogoutModel.h"

NS_ASSUME_NONNULL_BEGIN

// Initial User Identity
typedef void(^UserIdentityInitialBlock)(HJUserIdentityInitialModel *userIdentityInitialModel, NSString *errorMsg);
// Report Device Info(CLP).
typedef void(^ReportDeviceInfoBlock)(HJDeviceReportModel *deviceReportModel, NSString *errorMsg);
// User Identity Logout
typedef void(^UserIdentityLogoutBlock)(HJUserIdentityLogoutModel *userIdentityLogoutModel, NSString *errorMsg);



@interface HJUserLogic : NSObject<HJVMRequestDelegate>

/// eg:Initial User Identity
/// @param prefix  The prefix associated with the subscriber's service number. (Optional)
/// @param custNbr The unique customer code, used for uniquely identifying the customer in business operations. (required)
/// @param serviceNumber The service number associated with the subscriber.(Optional)
/// @param subsId  The unique identifier for the subscriber.(Optional)
- (void)queryUserIdentityInitialWithPrefix:(NSString *)prefix custNbr:(NSString *)custNbr serviceNumber:(NSString *)serviceNumber subsId:(NSString *)subsId block:(UserIdentityInitialBlock)userIdentityInitialBlock;

/// eg:Report Device Info(CLP).
/// @param pushToken Token generated by push service vender. (required)
/// @param pushServiceVendor Push service vender. Possible values are:/1- Firebase;/2 - Huawei
- (void)reportDeviceInfoWithPushToken:(NSString *)pushToken pushServiceVendor:(NSString *)pushServiceVendor block:(ReportDeviceInfoBlock)reportDeviceInfoBlock;

/// eg:User Identity Logout
/// @param pushToken Token generated by push service vender. (required)
/// @param pushServiceVendor Push service vender. Possible values are:/1- Firebase;/2 - Huawei
- (void)requestUserIdentityLogoutWithPushToken:(NSString *)pushToken pushServiceVendor:(NSString *)pushServiceVendor block:(UserIdentityLogoutBlock)userIdentityLogoutBlock;

@end

NS_ASSUME_NONNULL_END
